[atoms.OH_alcohol]
name = "OH_alcohol"
mass = 17.007
epsilon = 0.1673
sigma = 3.035
m = 12.0
cut = 14.0
charge = -0.65
style = "hybrid Mie/cut coul/long"

[atoms.CH2_alkane]
name = "CH2_alkane"
mass = 14.027
epsilon = 0.1051
sigma = 4.04
m = 14.0
cut = 14.0
charge = 0.0
style = "hybrid Mie/cut coul/long"

[atoms.CH2_alcohol]
name = "CH2_alcohol"
mass = 14.027
epsilon = 0.1673
sigma = 3.842
m = 14.0
cut = 14.0
charge = 0.246
style = "hybrid Mie/cut coul/long"

[atoms.CH2_EOH]
name = "CH2_EOH"
mass = 14.027
epsilon = 0.1515
sigma = 3.908
m = 14.0
cut = 14.0
charge = 0.252
style = "hybrid Mie/cut coul/long"

[atoms.OH_EOH]
name = "OH_EOH"
mass = 17.007
epsilon = 0.1515
sigma = 3.087
m = 12.0
cut = 14.0
charge = -0.667
style = "hybrid Mie/cut coul/long"

[atoms.cH_alcohol]
name = "H"
mass = 1.0
epsilon = 0.0
sigma = 1.0
m = 12.0
cut = 0.0
charge = 0.404
style = "hybrid Mie/cut coul/long"

[atoms.cH_EOH]
name = "H"
mass = 1.0
epsilon = 0.0
sigma = 1.0
m = 12.0
cut = 0.0
charge = 0.415
style = "hybrid Mie/cut coul/long"

[bonds."[CH2_alkane][CH2_alkane]"]
list = [ "CH2_alkane", "CH2_alkane",]
type = 1
p = [ 1.54, 1000.0,]
style = "harmonic"

[bonds."[CH2_alcohol][CH2_alcohol]"]
list = [ "CH2_alcohol", "CH2_alcohol",]
type = 1
p = [ 1.514, 1000.0,]
style = "harmonic"

[bonds."[CH2_EOH][CH2_EOH]"]
list = [ "CH2_EOH", "CH2_EOH",]
type = 1
p = [ 1.514, 1000.0,]
style = "harmonic"

[bonds."[OH_EOH][cH_EOH]"]
list = [ "OH_EOH", "cH_EOH",]
type = 1
p = [ 0.97, 1000.0,]
style = "harmonic"

[bonds."[CH2_EOH][OH_EOH]"]
list = [ "CH2_EOH", "OH_EOH",]
type = 1
p = [ 1.42, 1000.0,]
style = "harmonic"

[bonds."[OH_alcohol][cH_alcohol]"]
list = [ "OH_alcohol", "cH_alcohol",]
type = 1
p = [ 0.97, 1000.0,]
style = "harmonic"

[bonds."[CH2_alcohol][OH_alcohol]"]
list = [ "CH2_alcohol", "OH_alcohol",]
type = 1
p = [ 1.42, 1000.0,]
style = "harmonic"

[bonds."[CH2_alcohol][CH2_alkane]"]
list = [ "CH2_alkane", "CH2_alcohol",]
type = 1
p = [ 1.514, 1000.0,]
style = "harmonic"

[angles."[CHxx_alkane][CH2_alkane][CHxx_alkane]"]
list = [ "CHxx_alkane", "CH2_alkane", "CHxx_alkane",]
type = 2
p = [ 114.0, 62.0586,]
style = "harmonic"

[angles."[CH2_alcohol][OH_alcohol][cH_alcohol]"]
list = [ "CH2_alcohol", "OH_alcohol", "cH_alcohol",]
type = 2
p = [ 107.4, 45.6354,]
style = "harmonic"

[angles."[CH2_alkane][CH2_alcohol][OH_alcohol]"]
list = [ "CH2_alkane", "CH2_alcohol", "OH_alcohol",]
type = 2
p = [ 113.5, 61.8104,]
style = "harmonic"

[angles."[CH2_alcohol][CH2_alcohol][OH_alcohol]"]
list = [ "CH2_alcohol", "CH2_alcohol", "OH_alcohol",]
type = 2
p = [ 113.5, 61.8104,]
style = "harmonic"

[angles."[CH2_alcohol][CH2_alkane][CHxx_alkane]"]
list = [ "CHxx_alkane", "CH2_alkane", "CH2_alcohol",]
type = 2
p = [ 114.0, 62.0586,]
style = "harmonic"

[angles."[CH2_alcohol][CH2_alkane][CH2_alcohol]"]
list = [ "CH2_alcohol", "CH2_alkane", "CH2_alcohol",]
type = 2
p = [ 114.0, 62.0586,]
style = "harmonic"

[angles."[CH2_EOH][OH_EOH][cH_EOH]"]
list = [ "CH2_EOH", "OH_EOH", "cH_EOH",]
type = 2
p = [ 107.4, 45.6354,]
style = "harmonic"

[angles."[CH2_EOH][CH2_EOH][OH_EOH]"]
list = [ "CH2_EOH", "CH2_EOH", "OH_EOH",]
type = 2
p = [ 113.5, 61.8104,]
style = "harmonic"

[torsions."[CHxx_alkane][CH2_alkane][CH2_alkane][CHxx_alkane]"]
list = [ "CHxx_alkane", "CH2_alkane", "CH2_alkane", "CHxx_alkane",]
type = 1
p = [ 0.0, 1.4101, -0.2708, 3.1429, 0.0,]
style = "opls"

[torsions."[CH2_alkane][CH2_alcohol][OH_alcohol][cH_alcohol]"]
list = [ "CH2_alkane", "CH2_alcohol", "OH_alcohol", "cH_alcohol",]
type = 1
p = [ -0.7347, 0.3257, 0.1465, 1.2068, 0.0,]
style = "opls"

[torsions."[CH2_alcohol][CH2_alcohol][OH_alcohol][cH_alcohol]"]
list = [ "CH2_alcohol", "CH2_alcohol", "OH_alcohol", "cH_alcohol",]
type = 1
p = [ -0.7347, 0.3257, 0.1465, 1.2068, 0.0,]
style = "opls"

[torsions."[CHxx_alkane][CH2_alkane][CH2_alcohol][OH_alcohol]"]
list = [ "CHxx_alkane", "CH2_alkane", "CH2_alcohol", "OH_alcohol",]
type = 1
p = [ 0.0, 0.82, -0.884, 4.3097, 0.0,]
style = "opls"

[torsions."[CH2_alcohol][CH2_alkane][CH2_alcohol][OH_alcohol]"]
list = [ "CH2_alcohol", "CH2_alkane", "CH2_alcohol", "OH_alcohol",]
type = 1
p = [ 0.0, 0.82, -0.884, 4.3097, 0.0,]
style = "opls"

[torsions."[CH2_alcohol][CH2_alkane][CH2_alkane][CHxx_alkane]"]
list = [ "CHxx_alkane", "CH2_alkane", "CH2_alkane", "CH2_alcohol",]
type = 1
p = [ 0.0, 1.4101, -0.2708, 3.1429, 0.0,]
style = "opls"

[torsions."[CH2_alcohol][CH2_alkane][CH2_alkane][CH2_alcohol]"]
list = [ "CH2_alcohol", "CH2_alkane", "CH2_alkane", "CH2_alcohol",]
type = 1
p = [ 0.0, 1.4101, -0.2708, 3.1429, 0.0,]
style = "opls"

[torsions."[OH_alcohol][CH2_alcohol][CH2_alcohol][OH_alcohol]"]
list = [ "OH_alcohol", "CH2_alcohol", "CH2_alcohol", "OH_alcohol",]
type = 6
p = [ 3.3966, -7.8358, 1.8155, 6.6448, -7.0705, -0.0781, 5.4748, 0.2415, 0.0,]
style = "nharmonic"
